AutoTestPlatform/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url
from AutoTestPlatform.views import index,login,loginout
urlpatterns = [
    url(r'^admin/', admin.site.urls), #后台管理模块
    url(r'^$', index), #首页
    url(r'^index/', index), #首页
    url(r'^login/',login),  #登陆
    url(r'^loginout/',loginout),#退出登录
    url(r'^apitest/',include(('apitest.urls','apitest'),namespace='apitest')),#接口测试模块
    url(r'^webtest/',include(('webtest.urls','webtest'),namespace='webtest')),#页面测试模块
    url(r'^project_env/',include(('project_env.urls','project_env'),namespace='project_env')),#项目&环境管理模块
    url(r'^taste_user/',include(('taste_user.urls','taste_user'),namespace='taste_user')),#任务&用户管理模块
]

apps/apitest/urls.py
from django.conf.urls import url
from apitest.views import get_interviews,add_interviews,del_interviews,update_interviews,search_interviews,download_file,upload_file
from apitest.views import get_testcase,add_testcase,search_testcase,update_testcase,del_testcase,find_prj_if,case_run
from apitest.views import get_plant,add_plant,update_plant,delete_plant,run_plan,query_report,search_plan
urlpatterns = [
    #接口管理
    url(r'^get_interviews/(?P<page_num>\d+)$',get_interviews.as_view(),name='get_interviews'),   #获取接口列表
    url(r'^search_interviews$',search_interviews.as_view(),name='search_interviews'),  #搜索接口
    url(r'^add_interviews$',add_interviews.as_view(),name='add_interviews'),  #添加接口
    url(r'^update_interviews$', update_interviews.as_view(), name='update_interviews'),  # 编辑接口
    url(r'^del_interviews$', del_interviews.as_view(), name='del_interviews'),  # 编辑接口
    url(r'^download_file$', download_file.as_view(), name='download_file'),  # 下载模版接口
    url(r'^upload_file$', upload_file.as_view(), name='upload_file'),  # 上传文件接口

    #用例管理
    url(r'^get_testcase/(?P<page_num>\d+)$', get_testcase.as_view(), name='get_testcase'),  # 获取用例列表
    url(r'^add_testcase$', add_testcase.as_view(), name='add_testcase'),  # 添加用例
    url(r'^search_testcase$', search_testcase.as_view(), name='search_testcase'),  # 搜索用例
    url(r'^update_testcase$', update_testcase.as_view(), name='update_testcase'),  # 编辑用例
    url(r'^del_testcase$', del_testcase.as_view(), name='del_testcase'),  # 编辑用例
    url(r'^find_prj_if$', find_prj_if.as_view(), name='find_prj_if'),  # 查找项目下对应的接口
    url(r'^case_run$',case_run.as_view(),name='case_run'), #案例运行接口

    #测试计划管理
    url(r'^get_plant/(?P<page_num>\d+)$',get_plant.as_view(),name='get_plant'), #获取测试计划列表页
    url(r'^search_plan$',search_plan.as_view(),name='search_plan'), #主页搜索测试计划
    url(r'^add_plant$',add_plant.as_view(),name='add_plant'),#添加测试计划
    url(r'^update_plant$',update_plant.as_view(),name='update_plant'),#更新测试计划
    url(r'^delete_plant$',delete_plant.as_view(),name='delete_plant'),#删除测试计划
    url(r'^run_plan$',run_plan.as_view(),name='run_plan'),#运行测试计划
    url(r'^query_report$',query_report.as_view(),name='query_report'),#查看测试报告
]

apps/apitest/models.py
from django.db import models
class Interface(models.Model):
    '''接口类'''
    if_id=models.AutoField(primary_key=True, null=False,verbose_name='接口id')
    if_name=models.CharField(max_length=50,verbose_name='接口名称')
    if_url=models.CharField(max_length=50,verbose_name='接口地址')
    method=models.CharField(max_length=4,verbose_name='接口请求方法')
    data_type = models.CharField(max_length=4,verbose_name='接口请求头类型')
    project=models.ForeignKey('project_env.Project',on_delete=models.CASCADE,verbose_name='项目')
    description=models.CharField(max_length=50,verbose_name='接口描述')
    request_header_param=models.TextField(verbose_name='请求头')
    request_body_param = models.TextField(verbose_name='请求体')
    response_header_param = models.TextField(verbose_name='响应头')
    response_body_param = models.TextField(verbose_name='响应体')

    def __str__(self):
        return self.if_name
class Case(models.Model):
    '''测试用例类'''
    case_id=models.AutoField(primary_key=True, null=False,verbose_name='用例ID')
    case_name=models.CharField(max_length=50,verbose_name='用例名称')
    project=models.ForeignKey('project_env.Project',on_delete=models.CASCADE,verbose_name='项目')
    description=models.CharField(max_length=50,verbose_name='用例描述')
    content=models.TextField(verbose_name='用例内容')

    def __str__(self):
        return self.case_name
class Plan(models.Model):
    '''测试计划类'''
    plant_id=models.AutoField(primary_key=True, null=False,verbose_name='计划id')
    plant_name=models.CharField(max_length=50,verbose_name='计划名称')
    project=models.ForeignKey('project_env.Project',on_delete=models.CASCADE,verbose_name='项目')
    env=models.ForeignKey('project_env.Environment',on_delete=models.CASCADE,verbose_name='环境')
    description = models.CharField(max_length=50,verbose_name='计划描述')
    content=models.TextField(verbose_name='计划内容')

    def __str__(self):
        return self.plant_name
class Report(models.Model):
    '''测试报告类'''
    report_id=models.AutoField(primary_key=True, null=False,verbose_name='报告ID')
    report_name=models.CharField(max_length=50,verbose_name='报告名称')
    plant=models.ForeignKey('Plan',on_delete=models.CASCADE,verbose_name='报告对应的计划',null=True)
    content = models.TextField(verbose_name='报告内容')
    case_num=models.IntegerField(null=True,verbose_name='用例数量')
    pass_num = models.IntegerField(null=True,verbose_name='通过数量')
    fail_num = models.IntegerField(null=True,verbose_name='失败数量')
    error_num = models.IntegerField(null=True,verbose_name='错误数量')
    task=models.ForeignKey('taste_user.Taste',on_delete=models.CASCADE,verbose_name='报告对应的任务',null=True)

    def __str__(self):
        return self.report_name

apps/apitest/views.py
from django.shortcuts import render,redirect,HttpResponse
from django.http import JsonResponse
from db.mixin import LoginRequiredMixin
from django.urls import reverse
from django.db.models import Q
import json,time,os
from AutoTestPlatform.settings import BASE_DIR,UPLOAD_ROOT
from lib.execute import Execute
from lib.excelmethod import excelOpern
from django.views.generic import View
from django.http import FileResponse
from apitest.models import Interface,Case,Plan,Report
from project_env.models import Project,Environment
from taste_user.models import User,Taste
from django.core.paginator import Paginator
class get_interviews(LoginRequiredMixin,View):
    def get(self,requests,page_num):
        '''获取接口管理列表视图'''
        user=requests.user
        if user.is_superuser:
            interfaces_lists = Interface.objects.all()  # 获取到当前登陆用户所属项目对应的接口对象
        else:
            interfaces_lists=Interface.objects.filter(project__user__user_id=user.user_id)  #获取到当前登陆用户所属项目对应的接口对象
        page_obj=Paginator(interfaces_lists,per_page=8) #对现有数据实例化出一个每页展示2条的分页对象
        page_num_obj=page_obj.page(int(page_num))   #获取具体页面的对象
        active_number=page_num_obj.number         #当前活动页数
        page_num_obj_lists=page_num_obj.object_list    #具体页面的对象数据列表
        number_range=page_obj.page_range    #现有数据可分的页码数
        content={
            "number_range":number_range,
            "page_num_obj_lists":page_num_obj_lists,
            "active_number":active_number,
            "page_num_obj":page_num_obj,
            "user_obj":user
        }
        return render(requests,'apitest/interface_index.html',content)


class add_interviews(LoginRequiredMixin,View):
    def get(self,requests):
        '''获取添加接口页面'''
        projects=Project.objects.all()
        content={
            "projects":projects
        }
        return render(requests,'apitest/interface_add.html',content)

    def post(self,requests):
        '''添加接口'''
        if_name=requests.POST.get("if_name")   #接口名称
        prj_id=requests.POST.get("prj_id")     #项目id
        project=Project.objects.get(prj_id=prj_id) #项目对象
        url=requests.POST.get("url")           #接口url
        exit_obj = Interface.objects.filter(Q(if_url=url) & Q(project=project))
        method=requests.POST.get("method")     #请求方法
        data_type = requests.POST.get("data_type")  #传输类型
        description = requests.POST.get("description")  #接口描述
        request_header_data = requests.POST.get("request_header_data")  #请求头对象
        request_body_data = requests.POST.get("request_body_data")      #请求体对象
        response_header_data = requests.POST.get("response_header_data")  #响应头对象
        response_body_data = requests.POST.get("response_body_data")  # 相应体对象
        if exit_obj:
            return JsonResponse({'code':1,"data":"该环境下的接口已经存在了"})
        else:
            if_obj=Interface(if_name=if_name,if_url=url,method=method,data_type=data_type,project=project,description=description,
                  request_header_param=request_header_data,request_body_param=request_body_data,
                  response_header_param=response_header_data,response_body_param=response_body_data
                  )
            if_obj.save()
            # return redirect(reverse('apitest:get_interviews',kwargs={"page_num":1}))
            return JsonResponse({'code':2,"data":"添加接口成功"})


class del_interviews(LoginRequiredMixin,View):
    def get(self,requests):
        '''删除接口'''
        interface_id=requests.GET.get('interface_id')
        Interface.objects.get(if_id=interface_id).delete()
        return redirect(reverse('apitest:get_interviews',kwargs={"page_num":1}))
class update_interviews(LoginRequiredMixin,View):
    def get(self,requests):
        '''获取编辑页面'''
        interface_id=requests.GET.get('interface_id')
        if_obj=Interface.objects.get(if_id=interface_id)
        if if_obj.request_header_param.count(',')>=2:    #请求头
            request_header_list=if_obj.request_header_param[1:-1].split('},{')
            qingqoutou = [request_header_list[i] + "}" if i % 2 == 0 else "{" + request_header_list[i] for i in
                          range(len(request_header_list))]
            qingqoutou_lists = [json.loads(ii) for ii in qingqoutou]
        elif if_obj.request_header_param.count(',') == 1:
            qingqoutou_lists=json.loads(if_obj.request_header_param[1:-1])
        else:
            qingqoutou_lists= {}
        if if_obj.request_body_param.count(',')>=2:   #请求体
            request_body_lists = if_obj.request_body_param[1:-1].split('},{')
            requ_bo_lists = [request_body_lists[i] + "}" if i % 2 == 0 else "{" + request_body_lists[i] for i in
                             range(len(request_body_lists))]
            qingqouti_lists = [json.loads(ii) for ii in requ_bo_lists]
        elif if_obj.request_body_param.count(',') == 1:
            qingqouti_lists = json.loads(if_obj.request_body_param[1:-1])
        else:
            qingqouti_lists= {}
        if if_obj.response_header_param.count(',')>=2:   #相应头
            response_header_lists = if_obj.response_header_param[1:-1].split('},{')
            resp_he_lists = [response_header_lists[i] + "}" if i % 2 == 0 else "{" + response_header_lists[i] for i in
                             range(len(response_header_lists))]
            xiangyingtou_lists = [json.loads(ii) for ii in resp_he_lists]
        elif if_obj.response_header_param.count(',') == 1:
            xiangyingtou_lists = json.loads(if_obj.response_header_param[1:-1])
        else:
            xiangyingtou_lists= {}
        if if_obj.response_body_param.count(',')>=2:   #相应体
            response_body_lists = if_obj.response_body_param[1:-1].split('},{')
            resp_bo_lists = [response_body_lists[i] + "}" if i % 2 == 0 else "{" + response_body_lists[i] for i in
                             range(len(response_body_lists))]
            xiangyingti_lists = [json.loads(ii) for ii in resp_bo_lists]
        elif if_obj.response_body_param.count(',') == 1:
            xiangyingti_lists = json.loads(if_obj.response_body_param[1:-1])
        else:
            xiangyingti_lists={}
        prjs=Project.objects.all()
        content={
            "if_obj":if_obj,
            "prjs":prjs,
            "qingqoutou_lists":qingqoutou_lists,
            "qingqouti_lists": qingqouti_lists,
            "xiangyingtou_lists": xiangyingtou_lists,
            "xiangyingti_lists": xiangyingti_lists,
            "qingqiutou_flag":if_obj.request_header_param.count(','),
            "qingqiuti_flag":if_obj.request_body_param.count(','),
            "xiangyingtou_flag":if_obj.response_header_param.count(','),
            "xiangyingti_flag":if_obj.response_body_param.count(',')
        }
        return render(requests,'apitest/interface_update.html',content)
    def post(self,requests):
        '''进行编辑操作'''
        interface_id=requests.GET.get('if_obj_id')
        inter_info=Interface.objects.filter(if_id=interface_id)
        if_name=requests.POST.get('if_name') #接口名称
        prj_id=requests.POST.get('prj_id')   #编辑接口的ID
        url=requests.POST.get('url')     #URL
        project=Project.objects.get(prj_id=prj_id)   #接口所属的项目
        exit_obj = Interface.objects.filter(Q(if_url=url) & Q(project=project))
        method = requests.POST.get("method")  # 请求方法
        data_type = requests.POST.get("data_type")  # 传输类型
        description = requests.POST.get("description")  # 接口描述
        request_header_data = requests.POST.get("request_header_data")  # 请求头对象
        request_body_data = requests.POST.get("request_body_data")  # 请求体对象
        response_header_data = requests.POST.get("response_header_data")  # 响应头对象
        response_body_data = requests.POST.get("response_body_data")  # 相应体对象
        if exit_obj and inter_info[0].if_url != url and inter_info[0].project.prj_id != prj_id:
            return JsonResponse({'code':1,"data":"该环境下的接口已经存在了"})
        else:
            inter_info.update(if_name=if_name, if_url=url, method=method, data_type=data_type, project=project,
                               description=description,
                               request_header_param=request_header_data, request_body_param=request_body_data,
                               response_header_param=response_header_data, response_body_param=response_body_data
                               )
            return JsonResponse({'code':2,"data":"添加接口成功"})
class search_interviews(LoginRequiredMixin,View):
    def get(self,requests):
        '''搜索接口，入参为接口名称'''
        serach_interface_name = requests.GET.get('interface_name')
        user=requests.user
        if user.is_superuser:
            serach_interface_obj = Interface.objects.filter(if_name=serach_interface_name)
        else:
            serach_interface_obj = Interface.objects.filter(if_name=serach_interface_name,project__user__user_id=user.user_id)
        content={
            "page_num_obj_lists":serach_interface_obj,
            "user_obj": user
        }
        return render(requests,'apitest/interface_index.html',content)
class download_file(LoginRequiredMixin,View):
    def get(self,requests):
        '''下载接口模版'''
        file=open(os.path.join(BASE_DIR,'static/file',"接口模版.xlsx"),'rb')
        response = FileResponse(file)
        response['Content-Type'] = 'application/octet-stream'
        response['Content-Disposition'] = 'attachment;filename="template.xlsx"'
        return response
class upload_file(LoginRequiredMixin,View):
    def post(self,request):
        '''上传的文件入库'''
        file_obj=request.FILES.get('select_file')
        if not os.path.exists(UPLOAD_ROOT):
            os.makedirs(UPLOAD_ROOT)
        try:
            if file_obj is None:
                return HttpResponse('请选择要上传的文件！')
            #循环二进制文件写入 chunk方法是块级读取写入文件
            f=open(os.path.join(BASE_DIR,UPLOAD_ROOT,file_obj.name),'wb')
            for chunk in file_obj.chunks():
                f.write(chunk)
            f.close()
        except Exception as e:

templates/apitest/interface_index.html
{% extends "base.html" %}
{% load static %}
{% block crumbs %}
    <div class="row">
        <div class="col-md-12">
            <ol class="breadcrumb">
                <li>
                    <a href="/index">主页</a>
                </li>
                <li class="active">
                    <a class="this-page">接口测试</a>
                </li>
                <li class="active">
                    <a class="this-page">接口测管理</a>
                </li>
            </ol>

        </div>
    </div>
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-12">
            <div class="panel">
                <div class="panel-heading">
                    <input type="text" id="sear_interface_name" style="border:2px solid #337ab7;width:30%;height:30px;" name="interface_name" placeholder="接口名称">
                    <input type="button" id="sear" class="btn btn-primary" name="search" value="搜索">
                    <script type="text/javascript" src="{% static 'scripts/jquery-1.12.4.min.js' %}"></script>
                    <script type="text/javascript">
                        $(function () {
                            $('#sear').click(function(){
                                var interface_name=$('#sear_interface_name').val()
                                if(interface_name==""){
                                    location.href='{% url 'apitest:get_interviews' 1 %}'
                                }else{
                                    location.href='{% url 'apitest:search_interviews' %}?interface_name='+interface_name+''
                                }
                            })
                            })
                    </script>
                    <a href="{% url 'apitest:add_interviews' %}" style="position: absolute;right:160px;top:20px" class="btn btn-primary">添加接口</a>
                    <a href="#" style="position: absolute;right:100px;top:30px" id="select_id">导入</a>
                    <a href="{% url 'apitest:download_file' %}" style="position: absolute;right:30px;top:30px" >下载模版</a>

                </div>
                <div class="panel-body">
                    <table id="mytable" class="table table-bordered">
                        <thead>
                        <tr>
                            <th>接口名称</th>
                            <th>api地址</th>
                            <th>请求方法</th>
                            <th>所属项目</th>
                            <th>接口描述</th>
                            <th>操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for interface in page_num_obj_lists %}
                            <tr>
                                <td>{{ interface.if_name }}</td>
                                <td>{{ interface.if_url }}</td>
                                <td>{{ interface.method }}</td>
                                <td>{{ interface.project }}</td>
                                <td>{{ interface.description }}</td>
                                <td>
                                    <a href="{% url 'apitest:update_interviews' %}?interface_id={{ interface.if_id }}" class="layui-btn layui-btn-xs"
                                       lay-event="edit">编辑</a>
                                    <a href="{% url 'apitest:del_interviews' %}?interface_id={{ interface.if_id }}"
                                       class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">删除</a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="panel-footer">
                <nav aria-label="Page navigation">
                    <ul class="pagination pagination-sm">
                    {% if page_num_obj.has_previous %}
                        <li><a href="{% url 'apitest:get_interviews' page_num_obj.previous_page_number %}" aria-label="Previous">
                            <span aria-hidden="true">上一页</span></a></li>
                {% else %}
                <li class="disabled"><a aria-label="Previous"><span aria-hidden="true">上一页</span></a></li>
                    {% endif %}
                    {% for num in number_range %}
                        {% if num == active_number %}
                        <li class="active"><a href="">{{ num }}</a></li>
                        {% else %}
                        <li><a href="{% url 'apitest:get_interviews' num %}">{{ num }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if page_num_obj.has_next %}
                    <li><a href="{% url 'apitest:get_interviews' page_num_obj.next_page_number %}" aria-label="Next">
                        <span aria-hidden="true">下一页</span></a></li>
                      {% else %}
                      <li class="disabled"><a aria-label="Next"><span aria-hidden="true">下一页</span></a></li>
                    {% endif %}
                    </ul>
                </nav>
			</div>
            </div>

        </div>
    </div>
{% endblock %}
{% block javascript %}
    <script>
    $(function(){
        //jquery创建的一个文本选择器，因为并没有把它加载到页面，所以是不可见的
        var file=$('<input type="file" id="upload_file"/>');
        $("#select_id").click(function (){
            //启动文本选择
            file.click();
        });
        file.change(function(e){
            var file_obj=file[0].files[0];  //选择的文件对象,file[0]为jq对象转化为dom对象；
            var form=new FormData  //实例化FormData对象
            form.append("select_file",file_obj)
            event.target.value = null; //解决type="file" 只能上传一次的问题
            $.ajax({
                type:'post',
                url:'/apitest/upload_file',
                data:form,
                processData: false,  //上传文件的固定的写法  tell jquery not to process the data
                contentType: false,  //上传文件的固定的写法  tell jquery not to set contentType
                success:function (data){
                    if(data.code == 0){
                        alert(data.message)
                        $('#mytable').bootstrapTable('refresh');
                    }else{
                        alert(data.message)
                    }
                },
                error:function (){
                    toastr.warning("上传失败");
                }

            })

        })
    })
    </script>
{% endblock %}

templates/apitest/plant_index.html
{% extends "base.html" %}
{% load static %}
{% block crumbs %}
    <div class="row">
        <div class="col-md-12">
            <ol class="breadcrumb">
                <li>
                    <a href="/index">主页</a>
                </li>
                <li class="active">
                    <a class="this-page">接口测试</a>
                </li>
                <li class="active">
                    <a class="this-page">测试计划管理</a>
                </li>
            </ol>

        </div>
    </div>
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-12">
            <div class="panel">
                <div class="panel-heading">
                    <input type="text" id="sear_plan_name" style="border:2px solid #337ab7;width:30%;height:30px;" name="testcase_name" placeholder="计划名称">
                    <input type="button" id="sear" class="btn btn-primary" name="search" value="搜索" onclick="search(this)">
                    <script type="text/javascript" src="{% static 'scripts/jquery-1.12.4.min.js' %}"></script>
                    <a href="{% url 'apitest:add_plant' %}" style="position: absolute;right:30px;top:20px" class="btn btn-primary">添加计划</a>
                </div>
                <div class="panel-body">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>计划名称</th>
                            <th>所属项目</th>
                            <th>所属环境</th>
                            <th>包含用例</th>
                            <th>描述</th>
                            <th>操作</th>
                            <th>报告</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for plan in plan_objs %}
                         <tr>
                                <td>{{ plan.plant_id }}</td>
                                <td>{{ plan.plant_name }}</td>
                                <td>{{ plan.project }}</td>
                                <td>{{ plan.env }}</td>
                                <td>{{ plan.content }}</td>
                                <td>{{ plan.description }}</td>
                            <td>
                            <button class="btn btn-primary" onclick="run_button(this);">执行计划</button>
                            <a href="{% url 'apitest:update_plant' %}?plan_id={{ plan.pk }}" class="layui-btn layui-btn-xs"
                               lay-event="edit">编辑</a>
                            <a href="{% url 'apitest:delete_plant' %}?plan_id={{ plan.pk }}"
                               class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">删除</a>
                            </td>
                            <td>
                                <a class="btn btn-primary" href="{% url 'apitest:query_report' %}?plan_id={{plan.pk}}"><i class="fa fa-edit"></i>&nbsp;查看报告</a>
                            </td>
                    </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="panel-footer">
                <nav aria-label="Page navigation">
                    <ul class="pagination pagination-sm">
                    {% if page_num_obj.has_previous %}
                        <li><a href="{% url 'apitest:get_plant' page_num_obj.previous_page_number %}" aria-label="Previous">
                            <span aria-hidden="true">上一页</span></a></li>
                {% else %}
                <li class="disabled"><a aria-label="Previous"><span aria-hidden="true">上一页</span></a></li>
                    {% endif %}
                    {% for num in page_range %}
                        {% if num == active_num %}
                        <li class="active"><a href="">{{ num }}</a></li>
                        {% else %}
                        <li><a href="{% url 'apitest:get_plant' num %}">{{ num }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if page_num_obj.has_next  %}
                    <li><a href="{% url 'apitest:get_plant' page_num_obj.next_page_number %}" aria-label="Next">
                        <span aria-hidden="true">下一页</span></a></li>
                      {% else %}
                      <li class="disabled"><a aria-label="Next"><span aria-hidden="true">下一页</span></a></li>
                    {% endif %}
                    </ul>
                </nav>
			</div>
            </div>

        </div>
    </div>

{% endblock %}
{% block javascript %}
    <script>
        function search(obj){
            var plan_name=$("#sear_plan_name").val();
            if(plan_name==""){
                location.href='{% url 'apitest:get_plant' 1 %}'
            }else{
                location.href='{% url 'apitest:search_plan' %}?plan_name='+plan_name
            }
        };
        function run_button(obj){
            alert("开始运行,点击确定按钮后查看结果....")
            var plan_id=obj.parentNode.parentNode.children[0].innerText;
            var plan_name=obj.parentNode.parentNode.children[1].innerText;
            $.ajax({
                type:"post",
                url:"/apitest/run_plan",
                data:{
                    "plan_id":plan_id
                },
                success:function(result){
                    alert(result)
                },
                error(){
                    alert(plan_name+"执行失败")
                }
            });

        }
    </script>
{% endblock %}