AutoTestPlatform/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url
from AutoTestPlatform.views import index,login,loginout
urlpatterns = [
    url(r'^admin/', admin.site.urls), #后台管理模块
    url(r'^$', index), #首页
    url(r'^index/', index), #首页
    url(r'^login/',login),  #登陆
    url(r'^loginout/',loginout),#退出登录
    url(r'^apitest/',include(('apitest.urls','apitest'),namespace='apitest')),#接口测试模块
    url(r'^webtest/',include(('webtest.urls','webtest'),namespace='webtest')),#页面测试模块
    url(r'^project_env/',include(('project_env.urls','project_env'),namespace='project_env')),#项目&环境管理模块
    url(r'^taste_user/',include(('taste_user.urls','taste_user'),namespace='taste_user')),#任务&用户管理模块
]

apps/apitest/urls.py
from django.conf.urls import url
from apitest.views import get_interviews,add_interviews,del_interviews,update_interviews,search_interviews,download_file,upload_file
from apitest.views import get_testcase,add_testcase,search_testcase,update_testcase,del_testcase,find_prj_if,case_run
from apitest.views import get_plant,add_plant,update_plant,delete_plant,run_plan,query_report,search_plan
urlpatterns = [
    #接口管理
    url(r'^get_interviews/(?P<page_num>\d+)$',get_interviews.as_view(),name='get_interviews'),   #获取接口列表
    url(r'^search_interviews$',search_interviews.as_view(),name='search_interviews'),  #搜索接口
    url(r'^add_interviews$',add_interviews.as_view(),name='add_interviews'),  #添加接口
    url(r'^update_interviews$', update_interviews.as_view(), name='update_interviews'),  # 编辑接口
    url(r'^del_interviews$', del_interviews.as_view(), name='del_interviews'),  # 编辑接口
    url(r'^download_file$', download_file.as_view(), name='download_file'),  # 下载模版接口
    url(r'^upload_file$', upload_file.as_view(), name='upload_file'),  # 上传文件接口

    #用例管理
    url(r'^get_testcase/(?P<page_num>\d+)$', get_testcase.as_view(), name='get_testcase'),  # 获取用例列表
    url(r'^add_testcase$', add_testcase.as_view(), name='add_testcase'),  # 添加用例
    url(r'^search_testcase$', search_testcase.as_view(), name='search_testcase'),  # 搜索用例
    url(r'^update_testcase$', update_testcase.as_view(), name='update_testcase'),  # 编辑用例
    url(r'^del_testcase$', del_testcase.as_view(), name='del_testcase'),  # 编辑用例
    url(r'^find_prj_if$', find_prj_if.as_view(), name='find_prj_if'),  # 查找项目下对应的接口
    url(r'^case_run$',case_run.as_view(),name='case_run'), #案例运行接口

    #测试计划管理
    url(r'^get_plant/(?P<page_num>\d+)$',get_plant.as_view(),name='get_plant'), #获取测试计划列表页
    url(r'^search_plan$',search_plan.as_view(),name='search_plan'), #主页搜索测试计划
    url(r'^add_plant$',add_plant.as_view(),name='add_plant'),#添加测试计划
    url(r'^update_plant$',update_plant.as_view(),name='update_plant'),#更新测试计划
    url(r'^delete_plant$',delete_plant.as_view(),name='delete_plant'),#删除测试计划
    url(r'^run_plan$',run_plan.as_view(),name='run_plan'),#运行测试计划
    url(r'^query_report$',query_report.as_view(),name='query_report'),#查看测试报告
]

apps/taste_user/urls.py
from django.conf.urls import url
from taste_user.views import add_task,search_task,get_next_runtime,run_once,run,edit_task,delete_task,search_task_name
from taste_user.views import search_report,search_report_task_name
from taste_user.views import get_user
urlpatterns = [
    #定时任务管理
    url(r'^add_task$',add_task.as_view(),name='add_task'), #添加任务
    url(r'^search_task/(?P<page_num>\d+)$',search_task.as_view(),name='search_task'),#获取主列表页
    url(r'^get_next_runtime$', get_next_runtime.as_view(), name='get_next_runtime'),  # 获取下次运行时间
    url(r'^run_once$',run_once.as_view(),name='run_once'),#运行一次
    url(r'^run$',run.as_view(),name='run'),#执行、关闭
    url(r'^edit_task/(?P<page_num>\d+)$',edit_task.as_view(),name='edit_task'),  #编辑任务
    url(r'^delete_task$',delete_task.as_view(),name='delete_task'), #删除任务
    url(r'^search_task_name$',search_task_name.as_view(),name='search_task_name'),  #首页搜索接口

    #用户管理
    url(r'^get_user$',get_user.as_view(),name='get_user'),    #获取用户管理列表页面
    #测试报告管理
    url(r'^report/(?P<page_num>\d+)$',search_report.as_view(),name='search_report'), #获取测试报告首页
    url(r'^search_report_task$',search_report_task_name.as_view(),name='search_report_task') #首页搜索
]

apps/taste_user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
class Taste(models.Model):
    '''任务模型类'''
    status_choice={
        (0,'STOP'),
        (1,'RUNNING'),
        (2, 'PAUSE'),
        (3,'RESUME')
    }
    taste_id=models.AutoField(primary_key=True,null=False,verbose_name='任务ID')
    status=models.SmallIntegerField(default=0,choices=status_choice,verbose_name='任务状态')
    taste_name=models.CharField(max_length=20,verbose_name='任务名称')
    taste_time=models.CharField(max_length=30,verbose_name='任务日期')
    description=models.CharField(max_length=50,verbose_name='任务描述')
    project=models.ForeignKey('project_env.Project',on_delete=models.CASCADE,verbose_name='项目名称')
    env=models.ForeignKey('project_env.Environment',on_delete=models.CASCADE,verbose_name='环境名称')
    # plan=models.ForeignKey('apitest.Plan',on_delete=models.CASCADE,verbose_name='计划名称')
    plans=models.TextField(verbose_name='测试计划')
    # user=models.ForeignKey('User',on_delete=models.CASCADE,verbose_name='负责人')

    def __str__(self):
        return self.taste_name
class User(AbstractUser,models.Model):
    '''用户模型类'''
    user_id=models.AutoField(primary_key=True,null=False,verbose_name='用户ID')
    account=models.CharField(max_length=20,verbose_name='账号')
    # user_name=models.CharField(max_length=20,verbose_name='用户名称')
    # passward=models.CharField(max_length=20,verbose_name='密码')
    phone=models.CharField(max_length=11,verbose_name='手机号',unique=True)
    email=models.EmailField(max_length=30,verbose_name='邮箱号')
    #projects=models.ForeignKey('project_env.Project',on_delete=models.CASCADE,verbose_name='项目名称')
    project=models.ForeignKey('project_env.Project',on_delete=models.CASCADE,verbose_name='项目名称')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建日期')
    update_time = models.DateTimeField(auto_now=True, verbose_name='更新日期')
    roles=models.ManyToManyField("Role")
    def __str__(self):
        return self.username

class Role(models.Model):
    name=models.CharField(max_length=32)
    permissions=models.ManyToManyField("Permission")

    def __str__(self):
        return self.name
class Permission(models.Model):
    name=models.CharField(max_length=32)
    url=models.CharField(max_length=45)

    def __str__(self):
        return self.name

apps/taste_user/views.py
import datetime,time
import logging
logger = logging.getLogger("定时任务页")
from lib.execute import Execute
from lib.sendemail import sendEmail
from db.mixin import LoginRequiredMixin
from lib.sendtaskemail import send_email
from django.http import JsonResponse
from django.db.models import Q
from django.shortcuts import render,redirect,HttpResponse,reverse
from taste_user.models import Taste,User
from django.core.paginator import Paginator
from apitest.models import Plan,Report
from project_env.models import Project,Environment
from django.views.generic import View
from django.contrib import messages
from lib.task import diango_task
from lib.commonmethod import get_time_by_nexttime,time_add
#定时任务
class add_task(LoginRequiredMixin,View):
    def get(self,requests):
        pro_objs=Project.objects.all() #项目对象
        content={
            "pro_objs":pro_objs
        }
        return render(requests,'taste_user/task_add.html',content)
    def post(self,requests):
        task_name=requests.POST.get("task_name")
        prj_id=requests.POST.get("prj_id")
        env_id = requests.POST.get("env_id")
        plan_ids=requests.POST.getlist("plan_id")
        prj=Project.objects.get(prj_id=prj_id)
        env=Environment.objects.get(env_id=env_id)
        # for plan_id in plan_ids:
        #     plan=Plan.objects.get(plant_id=plan_id)
        task_obj=Taste.objects.filter(taste_name=task_name,project=prj,env=env,plans=plan_ids)
        if task_obj:
            messages.error(requests,"项目已存在")
        else:
            description=requests.POST.get("description")
            # user_id=int(requests.POST.get("user_name"))
            # user_obj=User.objects.get(user_id=user_id)
            corn = requests.POST.get("datetimepicker")
            # for plan_id in plan_ids:
            #     plan = Plan.objects.get(plant_id=plan_id)
            Taste(taste_name=task_name,taste_time=corn,description=description,project=prj,env=env,plans=plan_ids).save()
            return redirect(reverse('taste_user:search_task',kwargs={"page_num":1}))
        return render(requests,'taste_user/task_add.html')

class search_task(LoginRequiredMixin,View):
    def get(self,requests,page_num):
        user = requests.user
        if user.is_superuser:
            tasks = Taste.objects.all()
        else:
            tasks=Taste.objects.filter(project__user__user_id=user.user_id)
        page_obj=Paginator(tasks,3) #创建一个每页2条数据的分页对象
        page_range=page_obj.page_range #总的页数
        page_num_objs=page_obj.page(int(page_num)) #得到具体页面的页面对象
        active_number=page_num_objs.number  #当前活动页码
        obj_lists=page_num_objs.object_list #当前活动页数据
        content={
            "page_range":page_range,
            "active_number":active_number,
            "obj_lists":obj_lists,
            "page_obj":page_num_objs,
            "user_obj":user

        }
        return render(requests,'taste_user/task_index.html',content)
class search_task_name(LoginRequiredMixin,View):
    '''主页搜索接口试图'''
    def get(self,requests):
        task_name=requests.GET.get("task_name")
        user=requests.user
        if user.is_superuser:
            task_objs=Taste.objects.filter(taste_name=task_name)
        else:
            task_objs=Taste.objects.filter(taste_name=task_name,project__user__user_id=user.user_id)
        content={
            "obj_lists":task_objs,
            "user_obj": user
        }
        return render(requests,'taste_user/task_index.html',content)
class edit_task(LoginRequiredMixin,View):
    '''编辑试图'''
    def get(self,requests,page_num):
        task_obj=Taste.objects.get(taste_id=page_num)
        prj_obj=Project.objects.all()
        content={
            "task_obj":task_obj,
            "prj_obj":prj_obj
        }
        return render(requests,'taste_user/task_edit.html',content)
    def post(self,requests,page_num):
        task_obj=Taste.objects.filter(taste_id=page_num)
        task_name=requests.POST.get("task_name")          #任务名称
        prj_id=requests.POST.get("prj_id")
        pro_obj=Project.objects.get(prj_id=prj_id)     #系统对象
        env_id=requests.POST.get("env_id")
        env_obj=Environment.objects.get(env_id=env_id)   #环境对象
        description=requests.POST.get("description")     #任务描述
        corn=requests.POST.get("datetimepicker")   #任务时间
        corn=datetime.datetime.strptime(corn,'%Y-%m-%d:%H')
        plan_ids = requests.POST.getlist("plan_id")      #计划ID列表
        task_obj.update(taste_name=task_name,taste_time=corn,description=description,project=pro_obj,env=env_obj,plans=plan_ids)
        return redirect(reverse('taste_user:search_task',kwargs={"page_num":1}))
class delete_task(LoginRequiredMixin,View):
    '''删除试图'''
    def get(self,requests):
        page_num=requests.GET.get("task_id")
        try:
            Taste.objects.filter(taste_id=page_num).delete()
            return JsonResponse({"code":0,"msg":"删除成功"})
        except Exception as e:
            return JsonResponse({"code":1,"msg":"删除失败"})
class get_next_runtime(LoginRequiredMixin,View):
    '''获取下次运行日期'''
    def get(self,requests):
        task_id=requests.GET.get("task_id")
        task_obj=Taste.objects.filter(taste_id=task_id).values("taste_time")
        cron=list(task_obj)[0].get("taste_time")
        status = Taste.objects.filter(taste_id=task_id).values("status")
        if list(status)[0].get("status")==0 or list(status)[0].get("status")==2:
            num = get_time_by_nexttime(cron)
            new_date = str(time_add(cron, datetime.timedelta(days=num))).split(':')[0]
            return JsonResponse({'code':0,"result":"现在启动后下次的运行时间为："+str(new_date)})
        elif list(status)[0].get("status")==1 or list(status)[0].get("status")==3:
            num = get_time_by_nexttime(cron)
            new_date = str(time_add(cron,datetime.timedelta(days=num))).split(':')[0]
            return JsonResponse({'code':1,"result":new_date})
        else:
            return JsonResponse({'code':2,"result":"获取下次运行时间失败!!!"})
class run(LoginRequiredMixin,View):
    def post(self,requests):
        '''
        开启、关闭、重启 任务
        :param requests:1开启、2和4暂停、3重启    models:(0,'STOP'),(1,'RUNNING'),(2, 'PAUSE'),(3,'RESUME')
        :return: 返回ajax状态码用于前端更改任务状态
        '''
        status_flag=int(requests.POST.get("flag"))
        user = requests.POST.get("user")  # 用户ID
        task_id = requests.POST.get("task_id")  # 任务ID
        task_obj= Taste.objects.get(taste_id=task_id)
        time_obj= str(task_obj.taste_time).split(":")[1]
          # 任务对象
        uuid = "任务对象"+task_id
        task = diango_task()     #实例化定时任务对象
        logger.info("...............定时任务:%s 开始运行................."%task_obj.taste_name)
        task.addtask(run_task, uuid,time_obj, user, task_obj)
        if status_flag==1:
            task.starttask()              #开始定时执行
            Taste.objects.filter(taste_id=task_id).update(status=1)  #更改状态为running
            return JsonResponse({"code":1})
        elif status_flag==2 or status_flag==4:
            task.pausejob(uuid)      #暂停任务
            Taste.objects.filter(taste_id=task_id).update(status=2)  #更改状态pause
            return JsonResponse({"code":2})
        elif status_flag==3:
            task.resumejob(uuid)    # 重启任务
            Taste.objects.filter(taste_id=task_id).update(status=3)  #更改状态resume
            return JsonResponse({"code":3})
        else:
            task.removejob(uuid)
            return JsonResponse({"code":4})
class run_once(LoginRequiredMixin,View):
    '''运行一次'''
    def post(self,requests):
        user=requests.POST.get("user")  #用户ID
        task_id=requests.POST.get("task_id")   #任务ID
        task_obj = Taste.objects.get(taste_id=task_id) #任务对象
        task_report_obj=run_task(user,task_obj)
        # 有错误报告则发送邮件
        if task_report_obj.fail_num>0 or task_report_obj.error_num>0:
            # sendemail_obj=sendEmail(user_obj.email)
            # sendemail_obj.sendEmailFun("http://127.0.0.1:8001/",task_report_obj.task_id)
            # send_email(user_obj.email,"http://127.0.0.1:8001/",task_report_obj.task_id)
            return JsonResponse({"code":0,"message":"有失败或者错误的批次任务,请移至邮件查看详情！！！"})
        else:
            return JsonResponse({"code":1,"message":"测试报告已经生成,可在测试报告管理模块查看。"})

def run_task(user_id,task_obj):
    '''
    运行测试任务，生成对应的report
    :param task_id: 任务ID
    :return: 实例化后的report对象
    '''
    user_obj = User.objects.get(user_id=user_id)
    # task_obj = Taste.objects.get(taste_id=task_id)  # 任务对象
    env_id = task_obj.env.env_id  # 任务对象对应的环境
    plans = eval(task_obj.plans)  # 任务对应的计划list
    case_nums = 0  # 用例总数
    pass_num = 0  # 用例通过数
    fail_num = 0  # 用例失败数
    error_num = 0  # 用例错误数
    case_list = []  # 用例结果大list
    plan_obj_zanshi = None
    for plan in plans:
        plan_obj = Plan.objects.get(plant_id=plan)
        logger.info("该定时任务对应的测试计划：%s"%plan_obj.plant_name)
        cases = eval(plan_obj.content)
        case_nums += len(cases)
        for case in cases:
            logger.info("开始运行用例：%s"%case)
            execute_obj = Execute(case, env_id)
            run_result = execute_obj.run_case()
            case_list.append(run_result)
            if run_result["result"] == "pass":
                pass_num += 1
            elif run_result["result"] == "fail":
                fail_num += 1
            else:
                error_num += 1
    report_name = task_obj.taste_name + "-" + time.strftime("%Y%m%d%H%M%S")
    task_report_obj = Report(report_name=report_name, plant=plan_obj_zanshi, content=case_list, case_num=case_nums,
                             pass_num=pass_num, fail_num=fail_num, error_num=error_num, task=task_obj)
    task_report_obj.save()
    logger.info("已经生成对应的测试报告：%s"%task_report_obj.report_name)
    send_email(user_obj.email, "http://127.0.0.1:8001/", task_report_obj.task_id)
    logger.info("...........已经发送至对应邮箱，请注意查收.............")
    return task_report_obj

#测试报告
class search_report(LoginRequiredMixin,View):
    def get(self,requests,page_num):

templates/taste_user/report_index.html
{% extends "base.html" %}
{% load static %}
{% block body %}
    <div class="row">
        <div class="col-md-12">
            <div class="panel">
                <div class="panel-heading">
                    <input type="text" id="report_name" style="border:2px solid #337ab7;width:30%;height:30px;" name="report_name" placeholder="报告名称">
                    <input type="text" id="task_name" style="border:2px solid #337ab7;width:30%;height:30px;" placeholder="任务名称">
                    <input type="button" id="sear" class="btn btn-primary" name="search" value="搜索" onclick="search()">
                </div>
                <div class="panel-body">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>报告名称</th>
                            <th>日期</th>
                            <th>案例数</th>
                            <th>通过数</th>
                            <th>失败数</th>
                            <th>错误数</th>
                            <th>任务名称</th>
                            <th>操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for report in user_list %}
                         <tr class="btnstatus">
                                <td>{{ report.report_name }}</td>
                                <td>{{ report.time }}</td>
                                <td>{{ report.case_num }}</td>
                                <td>{{ report.pass_num }}</td>
                                <td>{{ report.fail_num }}</td>
                                <td>{{ report.error_num }}</td>
                                <td>{{ report.task }}</td>
                                 <td>
                                     <a href="{% url 'apitest:query_report' %}?report_id={{ report.report_id }}" class="layui-btn layui-btn-xs"
                                           lay-event="edit">查看详情</a>
                                 </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
    <div class="panel-footer">
    <nav aria-label="Page navigation">
			<ul class="pagination pagination-sm">
{#			{% if page_info.has_previous %}   {# 判断当前页是否有上一页#}
{#				<li><a href="{% url 'taste_user:search_report' page_info.previous_page_number %}" aria-label="Previous">#}
{#					<span aria-hidden="true">上一页</span></a></li>#}
{#            {% else %}#}
{#                <li class="disabled"><a aria-label="Previous"><span aria-hidden="true">上一页</span></a></li>#}
{#            {% endif %}#}
{#            {% for num in page_range%}   {# 循环遍历页码列表，并展示到底部 #}
{#            	{%if page_info.number == num%}#}
{#                	<li class="active"><a href="">{{ num }}</a></li>#}
{#                {%else%}#}
{#                    <li><a href="{% url 'taste_user:search_report' num %}">{{ num }}</a></li>#}
{#                {%endif%}#}
{#             {% endfor %}#}
{#             {% if page_info.has_next %}  {# 判断当前页是否有下一页#}
{#                 <li><a href="{% url 'taste_user:search_report' page_info.next_page_number %}" aria-label="Next">#}
{#                      <span aria-hidden="true">下一页</span></a></li>#}
{#             {% else %}#}
{#                 <li class="disabled"><a aria-label="Next"><span aria-hidden="true">下一页</span></a></li>#}
{#              {% endif %}#}
                {{ page_info.pager|safe }}
       		</ul>
    </nav>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block javascript %}
    <script>
        //搜索接口ajax
        function search(){
            var task_name=$("#task_name").val();
            var report_name=$("#report_name").val();
            if(task_name==""&&report_name==""){
                location.href='{% url 'taste_user:search_report' 1 %}'
            }else{
                location.href='{% url 'taste_user:search_report_task' %}?task_name='+task_name+'&report_name='+report_name
            }
        }

    </script>
{% endblock %}

templates/taste_user/task_add.html
{% extends "base.html" %}
{% load static %}
{% block crumbs %}
<div class="row">
    <div class="col-md-12">
        <ol class="breadcrumb">
            <li>
                <a href="/index">主页</a>
            </li>
            <li class="active">
                <a class="this-page" href="{% url 'taste_user:search_task' 1%}">定时管理</a>
            </li>
            <li class="active">
                <a class="">添加定时任务</a>
            </li>
        </ol>
    </div>
</div>
{% endblock %}
{% block body %}
    <div class="row">
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">添加定时任务</h3>
            </div>
            <div class="panel-body">
                <form class="form-horizontal" method="post" action="{% url 'taste_user:add_task' %}">
                    <div class="form-group">
                        <label class="col-sm-2 control-label">任务名称</label>
                        <div class="col-sm-6">
                            <input type="text" autocomplete="off" name="task_name" class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">选择项目</label>
                        <div class="col-sm-6">
                            <select class="form-control m-b" id="prj_id" name="prj_id" onchange=get_env()>
                                <option value="">请选择项目</option>
                                {% for pro in pro_objs %}
                                    <option value="{{ pro.prj_id }}">{{ pro.prj_name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">选择环境</label>
                        <div class="col-sm-6"><select class="form-control m-b" id="env_id" name="env_id" onclick="get_user()">
                        </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">任务描述</label>
                        <div class="col-sm-6">
                            <textarea name="description" placeholder="请输入内容" class="form-control" rows="3"></textarea>
                        </div>
                    </div>
{#                    <div class="form-group">#}
{#                        <label class="col-sm-2 control-label">选择负责人</label>#}
{#                        <div class="col-sm-6">#}
{#                            <select class="form-control m-b" id="user_id" name="user_name">#}
{#                                <option value="">请选择负责人</option>#}
{#                            </select>#}
{#                        </div>#}
{#                    </div>#}
                    <div class="form-group">
                        <label class="col-sm-2 control-label">开始执行时间</label>
                        <div class="col-sm-6">
                            <input type="text" id="data" autocomplete="off" name="datetimepicker" placeholder="选择日期" class="form-control">
                        </div>
                    </div>
                     <script type="text/javascript">
                            $("#data").empty();
                            var day=new Date();
                            $("#data").datetimepicker({
                                forceParse:0,
                                language:'zh-CN',
                                format:'yyyy-mm-dd:hh',
                                minView: 1,
                                initialDate:new Date(),
                                autoclose:true,
                                todayBtn:true,
                                datesDisabled:[day.getYear()+'-'+(day.getMonth()+1)+'-'+day.getDate(),day.getYear()+'-'+(day.getMonth()+1)+'-'+(day.getDate()+2)]
                            })
                            $("#date").datetimepicker("setDate", new Date() );
                     </script>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">计划列表</label>
                        <a id="plans" onclick="get_plan()" class="btn btn-primary">获取计划</a>
                        <div id="list" class="col-sm-10 col-sm-offset-2">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-6">
                            <button type="submit" class="btn btn-primary">保存</button>
                            <button type="reset" class="btn btn-primary">重置</button>
                        </div>
                    </div>
                </form>
            </div>

        </div>

    </div>

</div>
{% endblock %}
{% block javascript %}
    <script type="application/javascript">

        function get_env(){
            $("#env_id").empty();
            var prj_id = $("#prj_id").val();
            if (prj_id==null){
                alert("请先选择项目");
            }else{
                $.ajax({
                    type:"get",
                    url:"/apitest/find_prj_if",
                    data:{
                        "prj_id":prj_id,
                        "type":"get_env_by_prj_id"
                    },
                    success:function (data){
                        $(data).each(function (i,item){
                            $("#env_id").append("<option value="+item.env_id+">"+item.env_name+"</option>")
                        })
                    },
                    error:function (){
                        alert("获取环境失败！！！")
                    }
                });
            }

        }
        function get_user(){
            $("#user_id").empty();
            var prj_id=$("#prj_id").val();
            if(prj_id==null){
                alert("请先选择项目");
            }else{
                $.ajax({
                    type:"get",
                    url:"/apitest/find_prj_if",
                    data:{
                        "prj_id":prj_id,
                        "type":"get_user_by_prj_id"
                    },
                    success:function (result){
                        $(result).each(function (i,item){
                            $("#user_id").append("<option value="+item.user_id+">"+item.username+"</option>")
                        })
                    },
                    error:function (){
                        alert("获取项目下的负责人失败！！！")
                    }
                })
            }
        }
    function get_plan(){
            $("#list").empty();
            var prj_id=$("#prj_id").val();
            var env_id=$("#env_id").val();
            if(prj_id==null | env_id==null){
                alert("请先选择项目或环境");
            }else{
                $.ajax({
                    type:"get",
                    url: "/apitest/find_prj_if",
                    data: {
                        "prj_id":prj_id,
                        "env_id":env_id,
                        "type":"get_plan_by_prj_env_id"
                    },
                    success:function (data){
                        $(data).each(function (i,item){
                            $("#list").append("<label class='checkbox-inline'><input type='checkbox' name='plan_id' value="+ item.plant_id +">"+ item.plant_name +"</label>")
                        })
                    },
                    error:function(){
                        alert("获取项目下用例失败！！！")
                    }
                });
            }
    }
    </script>
{% endblock %}