AutoTestPlatform/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url
from AutoTestPlatform.views import index,login,loginout
urlpatterns = [
    url(r'^admin/', admin.site.urls), #后台管理模块
    url(r'^$', index), #首页
    url(r'^index/', index), #首页
    url(r'^login/',login),  #登陆
    url(r'^loginout/',loginout),#退出登录
    url(r'^apitest/',include(('apitest.urls','apitest'),namespace='apitest')),#接口测试模块
    url(r'^webtest/',include(('webtest.urls','webtest'),namespace='webtest')),#页面测试模块
    url(r'^project_env/',include(('project_env.urls','project_env'),namespace='project_env')),#项目&环境管理模块
    url(r'^taste_user/',include(('taste_user.urls','taste_user'),namespace='taste_user')),#任务&用户管理模块
]

apps/apitest/urls.py
from django.conf.urls import url
from apitest.views import get_interviews,add_interviews,del_interviews,update_interviews,search_interviews,download_file,upload_file
from apitest.views import get_testcase,add_testcase,search_testcase,update_testcase,del_testcase,find_prj_if,case_run
from apitest.views import get_plant,add_plant,update_plant,delete_plant,run_plan,query_report,search_plan
urlpatterns = [
    #接口管理
    url(r'^get_interviews/(?P<page_num>\d+)$',get_interviews.as_view(),name='get_interviews'),   #获取接口列表
    url(r'^search_interviews$',search_interviews.as_view(),name='search_interviews'),  #搜索接口
    url(r'^add_interviews$',add_interviews.as_view(),name='add_interviews'),  #添加接口
    url(r'^update_interviews$', update_interviews.as_view(), name='update_interviews'),  # 编辑接口
    url(r'^del_interviews$', del_interviews.as_view(), name='del_interviews'),  # 编辑接口
    url(r'^download_file$', download_file.as_view(), name='download_file'),  # 下载模版接口
    url(r'^upload_file$', upload_file.as_view(), name='upload_file'),  # 上传文件接口

    #用例管理
    url(r'^get_testcase/(?P<page_num>\d+)$', get_testcase.as_view(), name='get_testcase'),  # 获取用例列表
    url(r'^add_testcase$', add_testcase.as_view(), name='add_testcase'),  # 添加用例
    url(r'^search_testcase$', search_testcase.as_view(), name='search_testcase'),  # 搜索用例
    url(r'^update_testcase$', update_testcase.as_view(), name='update_testcase'),  # 编辑用例
    url(r'^del_testcase$', del_testcase.as_view(), name='del_testcase'),  # 编辑用例
    url(r'^find_prj_if$', find_prj_if.as_view(), name='find_prj_if'),  # 查找项目下对应的接口
    url(r'^case_run$',case_run.as_view(),name='case_run'), #案例运行接口

    #测试计划管理
    url(r'^get_plant/(?P<page_num>\d+)$',get_plant.as_view(),name='get_plant'), #获取测试计划列表页
    url(r'^search_plan$',search_plan.as_view(),name='search_plan'), #主页搜索测试计划
    url(r'^add_plant$',add_plant.as_view(),name='add_plant'),#添加测试计划
    url(r'^update_plant$',update_plant.as_view(),name='update_plant'),#更新测试计划
    url(r'^delete_plant$',delete_plant.as_view(),name='delete_plant'),#删除测试计划
    url(r'^run_plan$',run_plan.as_view(),name='run_plan'),#运行测试计划
    url(r'^query_report$',query_report.as_view(),name='query_report'),#查看测试报告
]

apps/project_env/urls.py
from django.conf.urls import url
from project_env.views import get_Projects,add_Projects,delete_Projects,update_Projects,search_Projects
from project_env.views import get_env,add_env,delete_env,update_env,search_env

urlpatterns = [
    #项目
    url(r'^get_Projects/(?P<page_num>\d+)$',get_Projects.as_view(),name='get_Projects'),   #获取项目列表
    url(r'^add_Projects$',add_Projects.as_view(),name='add_Projects'),   #get获取添加项目页面，post添加项目信息
    url(r'^delete_Projects$',delete_Projects.as_view(),name='delete_Projects'),   #删除项目
    url(r'^update_Projects$',update_Projects.as_view(),name='update_Projects'),   #编辑项目
    url(r'^search_Projects$',search_Projects.as_view(),name='search_Projects'),   #搜索项目接口

    #环境
    url(r'^get_env/(?P<page_num>\d+)$',get_env.as_view(),name='get_env'),   #获取环境列表
    url(r'^search_env$',search_env.as_view(),name='search_env'),   #搜索环境接口
    url(r'^add_env$',add_env.as_view(),name='add_env'),   #get获取添加环境页面，post添加环境信息
    url(r'^update_env$', update_env.as_view(), name='update_env'),  # 编辑环境
    url(r'^delete_env$', delete_env.as_view(), name='delete_env'),  # 删除环境

]

apps/taste_user/urls.py
from django.conf.urls import url
from taste_user.views import add_task,search_task,get_next_runtime,run_once,run,edit_task,delete_task,search_task_name
from taste_user.views import search_report,search_report_task_name
from taste_user.views import get_user
urlpatterns = [
    #定时任务管理
    url(r'^add_task$',add_task.as_view(),name='add_task'), #添加任务
    url(r'^search_task/(?P<page_num>\d+)$',search_task.as_view(),name='search_task'),#获取主列表页
    url(r'^get_next_runtime$', get_next_runtime.as_view(), name='get_next_runtime'),  # 获取下次运行时间
    url(r'^run_once$',run_once.as_view(),name='run_once'),#运行一次
    url(r'^run$',run.as_view(),name='run'),#执行、关闭
    url(r'^edit_task/(?P<page_num>\d+)$',edit_task.as_view(),name='edit_task'),  #编辑任务
    url(r'^delete_task$',delete_task.as_view(),name='delete_task'), #删除任务
    url(r'^search_task_name$',search_task_name.as_view(),name='search_task_name'),  #首页搜索接口

    #用户管理
    url(r'^get_user$',get_user.as_view(),name='get_user'),    #获取用户管理列表页面
    #测试报告管理
    url(r'^report/(?P<page_num>\d+)$',search_report.as_view(),name='search_report'), #获取测试报告首页
    url(r'^search_report_task$',search_report_task_name.as_view(),name='search_report_task') #首页搜索
]

templates/base.html
{# 首页及左侧菜单栏 #}
<!doctype html>
<html lang="en">
{% load static %}
<head>
    <title>k-自动化测试平台</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <!-- VENDOR CSS -->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/linearicons/style.css' %}">
    <!-- MAIN CSS -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <!-- FOR DEMO PURPOSES ONLY. You should remove this in your project -->
    <link rel="stylesheet" href="{% static 'css/demo.css' %}">
    <!-- GOOGLE FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">
    <!-- ICONS -->
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/title.jpg' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'img/title.jpg' %}">
    <!--bootstrap table -->
    <script type="application/javascript" src="{% static 'bootstrap-table/bootstrap-table.js' %}" ></script>
    <!--datetimepicker-->
    <script type="text/javascript" src="{% static 'scripts/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'bootstrap-datetimepicker-master/js/bootstrap-datetimepicker.js' %}"></script>
    <link rel="stylesheet" href="{% static 'bootstrap-datetimepicker-master/css/bootstrap-datetimepicker.css' %}">
    <script src="{% static 'bootstrap-datetimepicker-master/js/locales/bootstrap-datetimepicker.zh-CN.js' %}"></script>
    <link rel="stylesheet" href="{% static 'echarts/admin.css' %}">
    <link rel="stylesheet" href="{% static 'echarts/amazeui.min.js' %}">
    <link rel="stylesheet" href="{% static 'echarts/app.css' %}">
    <link rel="stylesheet" href="{% static 'echarts/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'echarts/gailan.css' %}">
   </head>
    {% block css %}{% endblock %}

<body>
<!-- WRAPPER -->
<div id="wrapper">
    <!-- NAVBAR顶部导航区域 -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="brand">
            <a href="/index/" style="font-size:18px"><b>k-TestPlatform</b></a>
        </div>
        <div class="container-fluid">
            <div class="navbar-btn">
                <button type="button" class="btn-toggle-fullwidth"><i class="lnr lnr-arrow-left-circle"></i></button>
            </div>
            <div id="navbar-menu">
                <ul class="nav navbar-nav navbar-right">

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="{% static 'img/user.png' %}" class="img-circle" alt="Avatar">
                            <span>{{ user_obj.username }}</span> <i class="icon-submenu lnr lnr-chevron-down"></i></a>
                        <ul class="dropdown-menu">
                            <li><a data-toggle="modal" data-target="#usermessage"><i class="lnr lnr-envelope"></i> <span>Message</span></a></li>
                            <li><a href="#"><i class="lnr lnr-cog"></i> <span>Settings</span></a></li>
                            <li><a href="/loginout/"><i class="lnr lnr-exit"></i> <span>退出登录</span></a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="modal fade" id="usermessage" aria-hidden="true">
                    <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                    aria-hidden="true">×</span></button>
                            <h4 class="modal-title">{{ user.username }}</h4>
                        </div>
                        <div class="modal-body">
                            <div class="form-horizontal" method="post" action="">
                                <div class="form-group">
                                    <label class="col-sm-3 control-label">电话:</label>
                                    <div class="col-sm-3 control-label">{{ user.phone }}</div>
                                </div>

                                <div class="form-group">
                                    <label class="col-sm-3 control-label">邮箱:</label>
                                    <div class="col-sm-3 control-label">{{ user.email }}</div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-3 control-label">系统:</label>
                                    <div class="col-sm-3 control-label">{{ user.project.prj_name }}</div>
                                </div>

                                <div class="modal-footer">
                                    <button type="button" id="cancel_run" class="btn btn-default" data-dismiss="modal">
                                        关闭
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                </div>

    <div id="sidebar-nav" class="sidebar">
       <!-- 左侧sider -->
        <div class="sidebar-scroll">
            <nav>
                <ul class="nav">
                    <li><a href="/index" class=""><i class="lnr lnr-home"></i> <span>首页概览</span></a></li>
                    <li><a href="{% url 'project_env:get_Projects' 1 %}" class=""><i class="lnr lnr-file-add"></i> <span>项目管理</span></a></li>
                    <li><a href="{% url 'project_env:get_env' 1 %}" class=""><i class="lnr lnr-database"></i> <span>环境管理</span></a></li>
                    <li>
                        <a href="#baseinfo" data-toggle="collapse" class="collapsed"><i class="lnr lnr-link"></i>
                            <span>接口测试</span> <i class="icon-submenu lnr lnr-chevron-left"></i></a>
                        <div id="baseinfo" class="collapse ">
                            <ul class="nav">
                                <li><a href="{% url 'apitest:get_interviews' 1 %}" class="">接口管理</a></li>
                                <li><a href="{% url 'apitest:get_testcase' 1 %}" class="">用例管理</a></li>
                                <li><a href="{% url 'apitest:get_plant' 1 %}" class="">测试计划管理</a></li>
                            </ul>
                        </div>
                    </li>
                    <li>
                        <a href="#system" data-toggle="collapse" class="collapsed"><i class="lnr lnr-screen"></i> <span>页面测试</span>
                            <i class="icon-submenu lnr lnr-chevron-left"></i></a>
                        <div id="system" class="collapse ">
                            <ul class="nav">
                                <li><a href="/base/sign/" class="">待开发</a></li>

                            </ul>
                        </div>
                    </li>
                    <li><a href="{% url 'taste_user:search_task' 1 %}" class=""><i class="lnr lnr-list"></i> <span>定时管理</span></a></li>
                    <li><a href="/admin" class=""><i class="lnr lnr-users"></i> <span>用户管理</span></a></li>
                    <li><a href="{% url 'taste_user:search_report' 1 %}" class=""><i class="lnr lnr-book"></i> <span>测试报告</span></a></li>

                </ul>
            </nav>
        </div>
    </div>
    <!-- END LEFT SIDEBAR -->
    <!-- MAIN -->
    <div class="main">
        <div class="main-content">
            <div class="container-fluid">
            <!-- 面包屑 -->
                {% block crumbs %}
                {% endblock %}
            <!-- body -->
                {% block body %}
                {% endblock %}
            </div>
        </div>
    </div>

</div>

<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'vendor/jquery-slimscroll/jquery.slimscroll.min.js' %}"></script>
<script src="{% static 'scripts/klorofil-common.js' %}"></script>
<script>
    $(document).ready(function () {
        var a_name = $("a.this").text();
        var page_name = $("a.this-page").text();
        if (a_name) {
            $("span:contains(" + a_name + ")").parent('a').removeClass("collapsed");
            $("span:contains(" + a_name + ")").parent('a').addClass("active");
            if (page_name){
                $("a:contains(" + page_name + ")").parent('li').parent('ul').parent('div').removeClass("collapse");
                $("a:contains(" + page_name + ")").parent('li').parent('ul').parent('div').addClass("collapse in");
                $("a:contains(" + page_name + ")").addClass("active");
            }
        }
    });
</script>
{% block javascript %} {% endblock %}
</body>

</html>

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block body %}

    <div class="tpl-content-wrapper" style="margin-top: -20px;">
        <div class="row">
            <div class="dashboard-stat blue">
                <div class="visual">
                    <i class="am-icon-comments-o"></i>
                </div>
                <div class="details">
                    <div class="number">{{ project_num }}</div>
                    <div class="desc"> 项目</div>
                </div>
                <a class="more" href="{% url 'project_env:get_Projects' 1 %}"> 查看项目
                    <i class="m-icon-swapright m-icon-white"></i>
                </a>

            </div>

            <div class="dashboard-stat red">
                <div class="visual">
                    <i class="am-icon-bar-chart-o"></i>
                </div>
                <div class="details">
                    <div class="number">{{ interface_num }}</div>
                    <div class="desc"> 接口</div>
                </div>
                <a class="more" href="{% url 'apitest:get_interviews' 1 %}"> 查看接口
                    <i class="m-icon-swapright m-icon-white">
                    </i>
                </a>

            </div>

            <div class="dashboard-stat green">
                <div class="visual">
                    <i class="am-icon-apple"></i>
                </div>
                <div class="details">
                    <div class="number">
                        {{ case_num }}
                    </div>
                    <div class="desc"> 测试用例</div>
                </div>
                <a class="more" href="{% url 'apitest:get_testcase' 1 %}"> 查看用例
                    <i class="m-icon-swapright m-icon-white"></i>
                </a>
            </div>


            <div class="dashboard-stat purple">
                <div class="visual">
                    <i class="am-icon-android"></i>
                </div>
                <div class="details">
                    <div class="number"> {{ report_num }}</div>
                    <div class="desc"> 测试报告</div>
                </div>
                <a class="more" href="{% url 'taste_user:search_report' 1 %}"> 查看报告
                    <i class="m-icon-swapright m-icon-white"></i>
                </a>
            </div>

        </div>
        <div class="table-responsive">
            <strong>我的定时任务</strong>
            <table class="table table-condensed">
                <thead>
                <tr>
                    <th>定时任务名称</th>
                    <th>下次执行时间</th>
                    <th>任务运行状态</th>
                    <a class="more" href="{% url 'taste_user:search_task' 1 %}">查看详情</a>
                </tr>
                </thead>
                <tbody>
                {% for task in page_num_objs %}
                    <tr>
                        <td>{{ task.taste_name }}</td>
                        <td>{{ task.taste_time }}</td>
                        {% if task.status == 0 or task.status == 2 %}
                            <td>STOP</td>
                        {% elif task.status == 1 or task.status == 3 %}
                            <td>RUNNING</td>
                        {% endif %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <nav aria-label="Page navigation">
            <ul class="pagination pagination-sm">
                {% if page_num_objs.has_previous %}   {# 判断当前页是否有上一页#}
                    <li><a href="/index/?page_num={{ page_num_objs.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">上一页</span></a></li>
                {% else %}
                    <li class="disabled"><a aria-label="Previous"><span aria-hidden="true">上一页</span></a></li>
                {% endif %}
                {% for num in page_range %}   {# 循环遍历页码列表，并展示到底部 #}
                    {% if page_num_objs.number == num %}
                        <li class="active"><a href="/index/?page_num={{ num }}">{{ num }}</a></li>
                    {% else %}
                        <li><a href="/index/?page_num={{ num }}">{{ num }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if page_num_objs.has_next %}  {# 判断当前页是否有下一页#}
                    <li><a href="/index/?page_num={{ page_num_objs.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">下一页</span></a></li>
                {% else %}
                    <li class="disabled"><a aria-label="Next"><span aria-hidden="true">下一页</span></a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
{% endblock %}

templates/login.html
{% load static %}
<html>
<!DOCTYPE html>
<html lang="en" class="no-js">

    <head>

        <meta charset="utf-8">
        <title>登录(Login)</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <!-- CSS -->
        <link rel="stylesheet" href="{% static 'login/css/reset.css' %}">
        <link rel="stylesheet" href="{% static 'login/css/supersized.css' %}">
        <link rel="stylesheet" href="{% static 'login/css/style.css' %}">

        <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
            <script src="{% static 'login/js/html5.js' %}"></script>
        <![endif]-->

    </head>

    <body>

        <div class="page-container">
            <h1>登录(Login)</h1>
            <form action="/login/" method="post">
                <input type="text" name="username" class="username" placeholder="请输入您的用户名！">
                <input type="password" name="password" class="password" placeholder="请输入您的用户密码！">
{#                <input type="Captcha" class="Captcha" name="Captcha" placeholder="请输入验证码！">#}
                <button type="submit" class="submit_button">登录</button>
                <div class="error"><span>+</span></div>
            </form>
{#            <div class="connect">#}
{#                <p>快捷</p>#}
{#                <p>#}
{#                    <a class="facebook" href=""></a>#}
{#                    <a class="twitter" href=""></a>#}
{#                </p>#}
{#            </div>#}
        </div>

        <!-- Javascript -->
        <script src="{% static 'login/js/jquery-1.8.2.min.js' %}" ></script>
        <script src="{% static 'login/js/supersized.3.2.7.min.js' %}" ></script>
        <script src="{% static 'login/js/supersized-init.js' %}" ></script>
        <script src="{% static 'login/js/scripts.js' %}" ></script>

    </body>
<div style="text-align:center;">
</div>
</html>