AutoTestPlatform/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url
from AutoTestPlatform.views import index,login,loginout
urlpatterns = [
    url(r'^admin/', admin.site.urls), #后台管理模块
    url(r'^$', index), #首页
    url(r'^index/', index), #首页
    url(r'^login/',login),  #登陆
    url(r'^loginout/',loginout),#退出登录
    url(r'^apitest/',include(('apitest.urls','apitest'),namespace='apitest')),#接口测试模块
    url(r'^webtest/',include(('webtest.urls','webtest'),namespace='webtest')),#页面测试模块
    url(r'^project_env/',include(('project_env.urls','project_env'),namespace='project_env')),#项目&环境管理模块
    url(r'^taste_user/',include(('taste_user.urls','taste_user'),namespace='taste_user')),#任务&用户管理模块
]

apps/project_env/urls.py
from django.conf.urls import url
from project_env.views import get_Projects,add_Projects,delete_Projects,update_Projects,search_Projects
from project_env.views import get_env,add_env,delete_env,update_env,search_env

urlpatterns = [
    #项目
    url(r'^get_Projects/(?P<page_num>\d+)$',get_Projects.as_view(),name='get_Projects'),   #获取项目列表
    url(r'^add_Projects$',add_Projects.as_view(),name='add_Projects'),   #get获取添加项目页面，post添加项目信息
    url(r'^delete_Projects$',delete_Projects.as_view(),name='delete_Projects'),   #删除项目
    url(r'^update_Projects$',update_Projects.as_view(),name='update_Projects'),   #编辑项目
    url(r'^search_Projects$',search_Projects.as_view(),name='search_Projects'),   #搜索项目接口

    #环境
    url(r'^get_env/(?P<page_num>\d+)$',get_env.as_view(),name='get_env'),   #获取环境列表
    url(r'^search_env$',search_env.as_view(),name='search_env'),   #搜索环境接口
    url(r'^add_env$',add_env.as_view(),name='add_env'),   #get获取添加环境页面，post添加环境信息
    url(r'^update_env$', update_env.as_view(), name='update_env'),  # 编辑环境
    url(r'^delete_env$', delete_env.as_view(), name='delete_env'),  # 删除环境

]

apps/project_env/models.py
from django.db import models
class Project(models.Model):
    '''项目模型类'''
    status_choice={
        (0, '失效'),
        (1, '有效')
    }
    prj_id=models.AutoField(primary_key=True,null=False,verbose_name='项目id')
    prj_name=models.CharField(max_length=50,verbose_name='项目名称')
    version=models.CharField(max_length=20,verbose_name='项目版本')
    description=models.CharField(max_length=100,verbose_name='项目描述')
    status=models.SmallIntegerField(default=1,choices=status_choice,verbose_name='项目状态')

    def __str__(self):
        return self.prj_name
class Environment(models.Model):
    '''环境模型类'''
    status_choice={
        (0, '失效'),
        (1, '有效')
    }
    env_id=models.AutoField(primary_key=True,null=False,verbose_name='环境id')
    env_name=models.CharField(max_length=50,verbose_name='环境名字')
    url=models.CharField(max_length=100,verbose_name='环境url')
    description=models.CharField(max_length=100,verbose_name='环境描述')
    status=models.SmallIntegerField(default=1,choices=status_choice,verbose_name='环境状态')
    project=models.ForeignKey('Project',on_delete=models.CASCADE,verbose_name='项目名称')

    def __str__(self):
        return self.env_name

apps/project_env/views.py
import logging
logger = logging.getLogger("项目管理-环境管理")
from django.shortcuts import render,redirect
from django.urls import reverse
from db.mixin import LoginRequiredMixin
from django.core.paginator import Paginator
from django.views.generic import View
from project_env.models import Project,Environment
from django.contrib import messages
class get_Projects(LoginRequiredMixin,View):
    def get(self,requests,page_num):
        '''获取项目列表视图'''
        logger.info("查询项目列表页数为：%s"%page_num)
        user=requests.user
        if user.is_superuser:
            pro_list = Project.objects.all()  #管理员对应的项目对象
        else:
            pro_list=Project.objects.filter(user__user_id=user.user_id) #获取当前登陆的普通用户的的项目对象
        pageitor=Paginator(pro_list,5)  #创建一页十条的分页对象
        pages=pageitor.page(int(page_num))   #得到具体页数的页面对象
        numbers=pages.number               #当前活动页数
        new_pro_list=pages.object_list    #具体页数的页面数据
        page_nums=pageitor.page_range  #数据可分为的页码数
        #封装页面上下文
        content={
            "pages":pages,
            "page_nums":page_nums,
            "pro_list":new_pro_list,
            "numbers":numbers,
            "user_obj":user
        }
        logger.info("获取项目列表视图的上下文content:%s"%content)
        return render(requests,'project_env/index.html',content)

class add_Projects(LoginRequiredMixin,View):
    def get(self,requests):
        '''获取添加项目页面视图'''
        return render(requests,'project_env/add.html')
    def post(self,requests):
        '''增加项目'''
        #获取前端传入的入参
        logger.info("添加项目参数为：%s" % requests.POST)
        prj_name=requests.POST.get('prj_name')  #项目名称
        #校验项目名称是否重复，重复的项目名称新增失败
        name=Project.objects.filter(prj_name=prj_name)
        pro_description = requests.POST.get('description')  # 项目描述
        prj_version = requests.POST.get('prj_version')  # 项目版本
        pro_status = requests.POST.get('pro_status')  # 项目状态
        if name:
            messages.error(requests,"项目已存在")
        else:
            #项目实例化
            prj=Project(prj_name=prj_name,version=prj_version,description=pro_description,status=pro_status)
            prj.save()
            logger.info("项目%s新增成功！！！" % prj)
            return redirect(reverse('project_env:get_Projects',kwargs={"page_num":1}))
        return render(requests,'project_env/add.html',{"name":prj_name,"pro_description":pro_description,"prj_version":prj_version,"pro_status":pro_status,"message":"项目名称重复了"})


class delete_Projects(LoginRequiredMixin,View):
    def get(self,requests):
        '''删除项目(传入项目ID)'''
        pro_id=requests.GET.get('pro_id')
        Project.objects.filter(prj_id=pro_id).delete()
        logger.info("项目%s删除成功！！！" % pro_id)
        return redirect(reverse('project_env:get_Projects',kwargs={"page_num":1}))

class update_Projects(LoginRequiredMixin,View):
    def get(self,requests):
        '''get获取编辑页面(传入项目ID)数据返现'''
        pro_id=requests.GET.get("pro_id")   #实例化指定的项目对象
        project=Project.objects.filter(prj_id=pro_id)[0]
        content={
            "project":project,
        }
        return render(requests,'project_env/update.html',content)
    def post(self,requests):
        '''编辑信息提交'''
        pro_id=requests.GET.get("pro_id")
        pro_info=Project.objects.filter(prj_id=pro_id)
        logger.info("更新项目%s的更新参数为:%s" %(pro_info,requests.POST))
        prj_name=requests.POST.get("prj_name")           #修改 项目名称
        if Project.objects.filter(prj_name=prj_name) and prj_name!=pro_info[0].prj_name:
            messages.error(requests, "项目已存在")
        else:
            description=requests.POST.get("description")           #修改 项目描述
            prj_version=requests.POST.get("prj_version")           #修改 项目版本
            pro_status=requests.POST.get("pro_status")           #修改 项目状态
            pro_info.update(prj_name=prj_name,version=prj_version,description=description,status=pro_status)
            logger.info("更新项目完成！！！")
            return redirect(reverse('project_env:get_Projects', kwargs={"page_num": 1}))
        project = Project.objects.filter(prj_id=pro_id)[0]
        return render(requests,'project_env/update.html',{"project":project,"message":"项目名称重复了"})
class search_Projects(LoginRequiredMixin,View):
    def get(self,requests):
        '''根据项目名称搜索接口'''
        project_name=requests.GET.get("project_name")
        logger.info("根据项目名称%s搜索接口" % project_name)
        user=requests.user
        if user.is_superuser:
            pro_list=Project.objects.filter(prj_name=project_name)  #实例化要查询的项目对象
        else:
            pro_list = Project.objects.filter(prj_name=project_name,user__user_id=user.user_id)
        content={
            "pro_list":pro_list,
            "user_obj": user
        }
        logger.info("根据项目名称搜索接口的返回值上下文:%s" % content)
        return render(requests,'project_env/index.html',content)
#环境相关
class get_env(LoginRequiredMixin,View):
    def get(self,requests,page_num):
        '''获取环境列表视图'''
        user=requests.user
        if user.is_superuser:
            env_list = Environment.objects.all()  #获取到当前登陆用户对应的项目环境
        else:
            env_list=Environment.objects.filter(project__user__user_id=user.user_id) #获取到当前登陆用户对应的项目环境
        pageitor=Paginator(env_list,2)  #创建一页十条的分页对象
        pages=pageitor.page(int(page_num))   #得到具体页数的页面对象
        numbers=pages.number               #当前活动页数
        new_env_list=pages.object_list    #具体页数的页面数据
        page_nums=pageitor.page_range  #数据可分为的页码数
        #封装页面上下文
        content={
            "pages":pages,
            "page_nums":page_nums,
            "env_list":new_env_list,
            "numbers":numbers,
            "user_obj":user
        }
        logger.info("获取环境列表视图返回值上下文:%s" % content)
        return render(requests,'project_env/env_index.html',content)

class add_env(LoginRequiredMixin,View):
    def get(self,requests):
        '''获取添加环境页面'''
        pro_lists=Project.objects.all()
        content={
            "pro_lists":pro_lists
        }
        return render(requests,'project_env/env_add.html',content)
    def post(self,requests):
        '''添加环境'''
        logger.info("环境添加的参数:%s" % requests.POST)
        env_url=requests.POST.get("env_url")
        env=Environment.objects.filter(url=env_url)
        env_name = requests.POST.get("env_name")
        description = requests.POST.get("description")
        prj_id = requests.POST.get("prj_id")
        pro_lists=Project.objects.filter(prj_id=prj_id)
        env_status = requests.POST.get("env_status")
        if env :
            messages.error(requests,"环境地址host重复了")
        else:
            #实例化环境对象
            envs=Environment(env_name=env_name,url=env_url,description=description,status=env_status,project=pro_lists[0])
            envs.save()
            logger.info("新增环境完成！！！")
            return redirect(reverse('project_env:get_env',kwargs={"page_num":1}))
        return render(requests,'project_env/env_add.html',{"env_name":env_name,"description":description,"pro_lists":pro_lists,"env_url":env_url,"env_status":env_status,"message":"该环境地址库中已经存在"})

class delete_env(LoginRequiredMixin,View):
    def get(self,requests):
        '''删除环境'''
        env_id=requests.GET.get('env_id')
        Environment.objects.get(env_id=env_id).delete()
        logger.info("删除环境完成！！！")
        return redirect(reverse('project_env:get_env',kwargs={"page_num":1}))
class update_env(LoginRequiredMixin,View):
    def get(self,requests):
        '''获取编辑页面'''
        env_id=requests.GET.get("env_id")
        env=Environment.objects.get(env_id=env_id)
        content={
            "env":env,
            "projrcts":Project.objects.all()
        }
        return render(requests,'project_env/env_update.html',content)
    def post(self,requests):
        '''进行编辑接口操作'''
        env_id = requests.GET.get("env_id")
        env_info=Environment.objects.filter(env_id=env_id)
        env_url=requests.POST.get("env_url")
        if Environment.objects.filter(url=env_url) and env_info[0].url != env_url:
            messages.error(requests,"环境地址host重复了")
        else:
            env_name = requests.POST.get("env_name")
            description = requests.POST.get("description")
            env_pro = requests.POST.get("env_pro")
            pro=Project.objects.get(prj_id=env_pro)
            env_status = requests.POST.get("env_status")
            env_info.update(env_name=env_name,description=description,project=pro,url=env_url,status=env_status)
            return redirect(reverse('project_env:get_env', kwargs={"page_num": 1}))
        env=Environment.objects.get(url=env_url)
        projrcts=Project.objects.all()
        content={
            "env":env,
            "projrcts":projrcts,
            "message":"该环境地址库中已经存在"
        }
        return render(requests,'project_env/env_update.html',content)

class search_env(LoginRequiredMixin,View):
    def get(self,requests):
        '''搜索环境接口'''
        user=requests.user
        env_name=requests.GET.get("env_name")
        if user.is_superuser:
            env=Environment.objects.filter(env_name=env_name)
        else:
            env=Environment.objects.filter(env_name=env_name,project__user__user_id=user.user_id)
        content={
            "env_list":env,
            "user_obj": user
        }
        return render(requests,'project_env/env_index.html',content)

templates/project_env/add.html
{% extends "base.html" %}
{% load static %}
{% block crumbs %}
<div class="row">
    <div class="col-md-12">
        <ol class="breadcrumb">
            <li>
                <a href="/index">主页</a>
            </li>
            <li class="active">
                <a class="this-page" href="{% url 'project_env:get_Projects' 1 %}">项目管理</a>
            </li>
            <li class="active">
                <a class="">添加项目</a>
            </li>
        </ol>

    </div>
</div>
{% endblock %}

{% block body %}


<div class="row">
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">添加项目</h3>
            </div>
            <div class="panel-body">
                <form class="form-horizontal" method="post" action="{% url 'project_env:add_Projects' %}">
                    <div class="form-group">
                        <label class="col-sm-2 control-label">项目名称</label>
                        <div class="col-sm-6">
                            <input type="text" autocomplete="off" name="prj_name" class="form-control" value={{ name }}>
                        </div>
                        <div id="b" style="color:red">{{ message }}</div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">项目描述</label>
                        <div class="col-sm-6">
                            <textarea name="description" placeholder="请输入内容" class="form-control" rows="3">{{ pro_description }}</textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">项目版本</label>
                        <div class="col-sm-6">
                            <input type="text" name="prj_version" class="form-control" value={{ prj_version }}>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">项目状态</label>
                        <div class="col-sm-6">
                            <select name="pro_status" class="form-control">
                                {% if pro_status == 1 %}
                                <option value="1">有效</option>
                                <option value="0">无效</option>
                                {% elif pro_status == 0 %}
                                <option value="0">无效</option>
                                <option value="1">有效</option>
                                 {% else %}
                                 <option value="1">有效</option>
                                <option value="0">无效</option>
                                {% endif %}
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-6">
                            <button type="submit" class="btn btn-primary">保存</button>
                        </div>
                    </div>
                </form>
            </div>

        </div>

    </div>

</div>

{% endblock%}

templates/project_env/env_add.html
{% extends "base.html" %}
{% load static %}
{% block crumbs %}
<div class="row">
    <div class="col-md-12">
        <ol class="breadcrumb">
            <li>
                <a href="/index">主页</a>
            </li>
            <li class="active">
                <a class="this-page" href="{% url 'project_env:get_env' 1 %}">环境管理</a>
            </li>
            <li class="active">
                <a class="">添加环境</a>
            </li>
        </ol>

    </div>
</div>
{% endblock %}

{% block body %}


<div class="row">
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">添加环境</h3>
            </div>
            <div class="panel-body">
                <form class="form-horizontal" method="post" action="{% url 'project_env:add_env' %}">
                    <div class="form-group">
                        <label class="col-sm-2 control-label">环境名称</label>
                        <div class="col-sm-6">
                            <input type="text" name="env_name" class="form-control" value={{ env_name }}>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">环境描述</label>
                        <div class="col-sm-6">
                            <textarea name="description" placeholder="请输入内容" class="form-control" rows="3">{{ description }}</textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">URL</label>
                        <div class="col-sm-6">
                            <input type="text" name="env_url" class="form-control" value={{ env_url }}>
                        </div>
                        <div id="b" style="color:red">{{ message }}</div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">所属项目</label>
                        <div class="col-sm-6">
                            <select name="prj_id" class="form-control">
                                {% for pro in pro_lists %}
                                    <option value={{ pro.prj_id }}>{{ pro.prj_name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">环境状态</label>
                        <div class="col-sm-6">
                            <select name="env_status" class="form-control">
                                {% if env_status == 1 %}
                                <option value="1">有效</option>
                                <option value="0">无效</option>
                                {% elif env_status == 0 %}
                                <option value="0">无效</option>
                                <option value="1">有效</option>
                                 {% else %}
                                 <option value="1">有效</option>
                                <option value="0">无效</option>
                                {% endif %}
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-6">
                            <button type="submit" class="btn btn-primary">保存</button>
                        </div>
                    </div>
                </form>
            </div>

        </div>

    </div>

</div>

{% endblock%}

templates/project_env/env_index.html
{% extends "base.html" %}
{% load static %}
{% block crumbs %}
    <div class="row">
        <div class="col-md-12">
            <ol class="breadcrumb">
                <li>
                    <a href="/index">主页</a>
                </li>
                <li class="active">
                    <a class="this-page">环境管理</a>
                </li>
            </ol>

        </div>
    </div>
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-12">
            <div class="panel">
                <div class="panel-heading">
                    <input type="text" id="sear_env_name" style="border:2px solid #337ab7;width:30%;height:30px; name="env_name" placeholder="环境名称">
                    <input type="button" id="sear" class="btn btn-primary" name="search" value="搜索">
                    <script type="text/javascript" src="{% static 'scripts/jquery-1.12.4.min.js' %}"></script>
                    <script type="text/javascript">
                        $(function () {
                            $('#sear').click(function(){
                                var env_name=$('#sear_env_name').val()
                                if(env_name==""){
                                    location.href='{% url 'project_env:get_env' 1 %}'
                                }else{
                                    location.href='{% url 'project_env:search_env' %}?env_name='+env_name+''
                                }
                            })
                            })
                    </script>
                    <a href="{% url 'project_env:add_env' %}" style="position: absolute;right:30px;top:20px" class="btn btn-primary">添加环境</a>
                </div>
                <div class="panel-body">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>环境名称</th>
                            <th>URL</th>
                            <th>环境描述</th>
                            <th>所属项目</th>
                            <th>环境状态</th>
                            <th>操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for env in env_list %}
                            <tr>
                                <td>{{ env.env_name }}</td>
                                <td>{{ env.url }}</td>
                                <td>{{ env.description }}</td>
                                <td>{{ env.project }}</td>
{#                                {% if env.status == 1 %}#}
{#                                    <td>有效</td>#}
{#                                    {% elif env.status == 0 %}#}
{#                                    <td>无效</td>#}
{#                                {% endif %}#}
                                <td>{{ env.get_status_display }}</td>
                                <td>
                                    <a href="{% url 'project_env:update_env' %}?env_id={{ env.env_id }}" class="layui-btn layui-btn-xs"
                                       lay-event="edit">编辑</a>
                                    <a href="{% url 'project_env:delete_env' %}?env_id={{ env.env_id }}"
                                       class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">删除</a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="panel-footer">
                <nav aria-label="Page navigation">
                    <ul class="pagination pagination-sm">
                    {% if pages.has_previous %}
                        <li><a href="{% url 'project_env:get_env' pages.previous_page_number %}" aria-label="Previous">
                            <span aria-hidden="true">上一页</span></a></li>
                {% else %}
                <li class="disabled"><a aria-label="Previous"><span aria-hidden="true">上一页</span></a></li>
                    {% endif %}
                    {% for num in page_nums %}
                        {% if num == numbers %}
                        <li class="active"><a href="">{{ num }}</a></li>
                        {% else %}
                        <li><a href="{% url 'project_env:get_env' num %}">{{ num }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if pages.has_next  %}
                    <li><a href="{% url 'project_env:get_env' pages.next_page_number %}" aria-label="Next">
                        <span aria-hidden="true">下一页</span></a></li>
                      {% else %}
                      <li class="disabled"><a aria-label="Next"><span aria-hidden="true">下一页</span></a></li>
                    {% endif %}
                    </ul>
                </nav>
			</div>
            </div>

        </div>
    </div>
{% endblock %}

templates/project_env/index.html
{% extends "base.html" %}
{% load static %}
{% block crumbs %}
    <div class="row">
        <div class="col-md-12">
            <ol class="breadcrumb">
                <li>
                    <a href="/index">主页</a>
                </li>
                <li class="active">
                    <a class="this-page">项目管理</a>
                </li>
            </ol>

        </div>
    </div>
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-12">
            <div class="panel">
                <div class="panel-heading">
                    <input type="text" id="sear_project_name" style="border:2px solid #337ab7;width:30%;height:30px;" name="project_name" placeholder="名称项目">
                    <input type="button" id="sear"  class="btn btn-primary" name="search" value="搜索">
                    <script type="text/javascript" src="{% static 'scripts/jquery-1.12.4.min.js' %}"></script>
                    <script type="text/javascript">
                        $(function () {
                            $('#sear').click(function(){
                                var project_name=$('#sear_project_name').val()
                                if(project_name==""){
                                    location.href='{% url 'project_env:get_Projects' 1 %}'
                                }else{
                                    location.href='{% url 'project_env:search_Projects' %}?project_name='+project_name+''
                                }
                            })
                            })
                    </script>
                    <a href="{% url 'project_env:add_Projects' %}" style="position: absolute;right:30px;top:20px" class="btn btn-primary">添加项目</a>
                </div>
                <div class="panel-body">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>项目名称</th>
                            <th>项目版本</th>
                            <th>项目描述</th>
                            <th>项目状态</th>
                            <th>操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for prj in pro_list %}
                            <tr>
                                <td>{{ prj.prj_name }}</td>
                                <td>{{ prj.version }}</td>
                                <td>{{ prj.description }}</td>
                                {% if prj.status == 1 %}
                                    <td>有效</td>
                                    {% elif prj.status == 0 %}
                                    <td>无效</td>
                                {% endif %}
                                <td>
                                    <a href="{% url 'project_env:update_Projects' %}?pro_id={{ prj.prj_id }}" class="layui-btn layui-btn-xs"
                                       lay-event="edit">编辑</a>
                                    <a href="{% url 'project_env:delete_Projects' %}?pro_id={{ prj.prj_id }}"
                                       class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">删除</a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            <div class="panel-footer">
            <nav aria-label="Page navigation">
                    <ul class="pagination pagination-sm">
                    {% if pages.has_previous %}
                        <li><a href="{% url 'project_env:get_Projects' pages.previous_page_number %}" aria-label="Previous">
                            <span aria-hidden="true">上一页</span></a></li>
                {% else %}
                <li class="disabled"><a aria-label="Previous"><span aria-hidden="true">上一页</span></a></li>
                    {% endif %}
                    {% for num in page_nums %}
                        {% if num == numbers %}
                        <li class="active"><a href="">{{ num }}</a></li>
                        {% else %}
                        <li><a href="{% url 'project_env:get_Projects' num %}">{{ num }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if pages.has_next  %}
                    <li><a href="{% url 'project_env:get_Projects' pages.next_page_number %}" aria-label="Next">
                        <span aria-hidden="true">下一页</span></a></li>
                      {% else %}
                      <li class="disabled"><a aria-label="Next"><span aria-hidden="true">下一页</span></a></li>
                    {% endif %}
                    </ul>
                </nav>
			</div>
            </div>

        </div>
    </div>
{% endblock %}